# Application

repo_dir: "Fun"

# Docker build
image_name: "webapp"
image_tag: "latest"
build_path: "{{ repo_dir }}"
dockerfile_path: "Dockerfile"

# Swarm service
service_name: "webapp"
replicas: 5
published_port: 3000
target_port: 3000

