---
# tasks file for app-build

- name: Clone application
  git:
    repo: "https://{{ git_user }}:{{ git_token }}@github.com/GhanshyamRamole/Fun.git"
    dest: "{{ repo_dir }}"
    force: yes

- name: Build Docker image
  community.docker.docker_image:
    name: "{{ image_name }}"
    tag: "{{ image_tag }}"
    source: build
    build:
      path: "{{ build_path }}"
      dockerfile: "{{ dockerfile_path }}"
      nocache: yes

